config/routes.rb
Rails.application.routes.draw do

  get '/adminv' , to: 'products#admin_view'

  get 'users/admin'

  get 'users/show'

  get 'orderpayement/:id' , to: 'charges#new', as: 'new_charge'

  post 'payementconfirmation/:id' , to: 'charges#create', as: 'charges'

  get 'carts/show'

  devise_for :users

  root 'products#index'

  get '/products/:id', to: 'products#show', as: 'product'

  get '/products/addtocart/:id', to: 'carts#addtocart', as: 'addtocart'

  get '/showcart', to: 'carts#show', as: 'showcart'

  get '/createorder', to: 'orders#createorder', as: 'createorder'

  get '/orders', to: 'orders#index', as: 'orders'

  delete '/cart/destroy', to: 'carts#destroy', as: 'cartdestroy'

  delete '/cart/destroyitem/:id', to: 'carts#deleteitem', as: 'destroyitem'

  delete '/orderdestroy/:id', to: 'orders#destroy', as: 'orderdestroy'

  get '/newitem', to: 'products#new'

  get 'users/:id',to: 'users#show', as: 'show_user'

  get '/adminv/edit/:id', to: 'products#edit', as:'edit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_and_belongs_to_many :carts
  has_and_belongs_to_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_one :cart
   has_many :items, through: :cart
   has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :sanitize_devise_params, if: :devise_controller?

  def sanitize_devise_params
    devise_parameter_sanitizer.permit(:sign_up) { |user| user.permit(
    :username,
    :email,
    :password,
    :password_confirmation,
    :order_id
    ) }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :require_login
  before_action :require_cart, only: [:show]

  def addtocart
      if current_user.cart
         current_user.cart.items << Item.find(params[:id])
      else
      cart=Cart.new
      cart.user=current_user
      cart.items<<Item.find(params[:id])
      cart.save
      end
      flash[:success] = "Article ajouté à votre panier"
      redirect_to root_path
  end

  def show
     @cart=current_user.cart.items
  end

    def deleteitem
      current_user.cart.items.delete(Item.find(params[:id]))
      redirect_to showcart_path
    end

  def destroy
    current_user.cart.items.clear
    redirect_to showcart_path
  end

  private

  def require_login
    unless user_signed_in?
      flash[:danger] = "Vous devez vous connecter pour accéder à votre panier"
      redirect_to new_user_session_path
    end
  end

def require_cart
  unless current_user.cart.present?
    flash[:danger] ="Veuillez ajouter quelque choses au panier"
    redirect_to root_path
  end
  end



end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @order = Order.find(params[:id])    
  end

  def create
    @amount = (Order.find(params[:id]).total_price*100).round(0)
    @order = Order.find(params[:id])

    customer = Stripe::Customer.create(
    email: params[:stripeEmail],
    source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
    customer: customer.id,
    amount: @amount ,
    description: 'Rails Stripe customer',
    currency: 'usd'
    )
    
    @order.statut = true
    @order.save!
    
    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :require_login

  def createorder
    order=Order.new
    order.user=current_user
    order.items=current_user.cart.items

    order.total_price=0
    order.items.each do |value|
      order.total_price+=value.price.round(2)
    end

    order.save
    current_user.cart.items.clear
    redirect_to orders_path
  end

  def index
    @orders=current_user.orders
  end

  def destroy
    order=Order.find(params[:id])
    order.destroy
    redirect_to root_path
  end

  private

  def require_login
    unless user_signed_in?
      flash[:danger] = "Vous devez vous connecter pour accéder à vos commandes"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @items = Item.all
  end

  def admin_view
    if current_user.admin?
    @items = Item.all
    @orders = Order.all
    else
    redirect_to root_path
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to @item
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  def show
    @item=Item.find(params[:id])
  end

  private
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def admin
    @user = User.find(params[:admin])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-8 cart">
      <h1>Mon panier</h1>
      <%if current_user.cart.items.count>0%>
      <div>
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">Article</th>
              <th scope="col">description</th>
              <th scope="col">prix</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% $total = 0 %>
            <%@cart.each do |value|%>
            <tr>
              <td><%=value.title%></td>
              <td><%=value.description%></td>
              <td><%=value.price%>€</td>
              <td>
                <%= link_to destroyitem_path(value.id),:class=>"btn btn-danger cart-button",:method => "delete" do %>
                <i class="fa fa-trash"></i>
                <% end %>
              </td>
              <% $total += value.price %>
            </tr>
            <%end%>
            <tr>
              <td></td>
              <td class="text-right" >Total:</td>
              <td><%=$total.round(2)%> €</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div>
        <%= link_to "Valider mon panier", createorder_path,:class=>"btn btn-success cart-button" %>
        <%= link_to "Vider mon panier", cartdestroy_path,:class=>"btn btn-danger cart-button", :method => "delete" %>
      </div>
      <%else%>
      <p> Votre panier est vide </p>
      <%end%>
    </div>
  </div>
</div>

<br>
<br>
<br>

app/views/charges/create.html.erb
<br>
<br>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-8 cart">
      <center>
      <h1>Thanks for payed</h1>
      <%= link_to "Commandes", orders_path, :class=>"btn btn-success cart-button" %>
      <%= link_to "Home", root_path,  :class=>"btn btn-success cart-button"%>
        <br><br>
      <a href="/"><img src="https://data.photofunky.net/output/image/3/2/1/7/321774/photofunky.gif" width="292" height="350"></a>
    </div>
  </div>
</div>
</center>

app/views/charges/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-8 cart">
      <h1>Ma Commande</h1>
      <%if current_user.cart.items.count>0%>
      <div>
        <table class="table">
          <thead class="thead-light">
            <tr>
            </tr>
          </thead>
          <tbody>
            <tr>
              <% $total += value.price %>
            </tr>
            <%end%>
            <tr>
              <td></td>

              <td><%= form_tag charges_path do %>
                <article>
                  <% if flash[:error].present? %>
                    <div id="error_explanation">
                      <p><%= flash[:error] %></p>
                    </div>
                  <% end %>
                  <label class="amount">
                    <span class="text-right">Total :<%= @order.total_price.round(2)%> € </span>
                  </label>
                </article></td>
            </tr>
            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                    data-description="A month's subscription"
                    data-email= "<%= current_user.email %>"
                    data-amount= "<%= @amount %>"
                    data-locale="auto"></script>
          <% end %>
          </tbody>
        </table>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>
  <title>Le Magasin de Photos de Chats !!</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>

</html>

app/views/orders/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-8 cart">
      <div>
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">Commande</th>
              <th scope="col">Montant total</th>
              <th scope="col">Statut</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <%@orders.each do |order|%>
            <tr>
              <td>
                <p>
                  <%order.items.each do |item|%>
                  <%=item.title%> /
                  <%end%>
              </td>
              <td><%=order.total_price.round(2)%></td>
              <% if order.statut == false %>
              <td>Unpayed</td>
              <td></td>
              <td><%= link_to "Payer", new_charge_path(order.id),  :class=>"btn btn-success cart-button" %>
              <%= link_to "Annuler", orderdestroy_path(order.id),:class=>"btn btn-danger cart-button", :method => "delete" %>
              </td>
              <%else%>
              <td>Complete</td>
              <td></td>
              <%end%>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/products/admin_view.html.erb
<p id="notice"><%= notice %></p>

<div class="alert alert-primary" role="alert">
  <center>
<h1>List of items</h1>
</center>
</div>
<%= link_to 'New item', newitem_path, :class=>"btn btn-outline-warning" %>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Titre</th>
      <th>Description</th>
      <th>Prix</th>
      <th>Poster</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.price %> €</td>
        <td><%= item.image_url %></td>
        <td><%= link_to 'Show', product_path(:id => item.id) %></td>
        <td><%= link_to 'Edit', edit_path(:id => item.id) %></td>
        <td><%= link_to 'Destroy', destroyitem_path(item.id), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Description</th>
      <th>Prix</th>
      <th>Email</th>
      <th>Order ID</th>
    </tr>
  </thead>

  <div class="alert alert-dark" role="alert">
<center>
<h1>List of orders</h1>
</center>
</div>
<tbody>
  <%@orders.each do |order|%>
  <tr>
    <td>
      <p>
        <%order.items.each do |item|%>
        <%=item.title%> /
        <%end%>
    </td>
    <td><%=order.total_price.round(2)%> €</td>
    <td><%=order.user.email%></td>
    <td><%=order.id%></td>
  </tr>
  <%end%>
</tbody>
</table>
<br>

app/views/products/edit.html.erb
<h1>Editer un Poster</h1>

<%= form_for @item, url: {action: "edit"}, html: {class: "nifty_form"} do |f| %>

  <p>
    <%= f.label :title%><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>


  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>


  <p>
    <%= f.label :image_url%><br>
    <%= f.text_field :image_url%>
  </p>


  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', adminv_path %>

app/views/products/index.html.erb
<div class="container">

  <div class="row ">

    <div class="col-lg-12">

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>

      <div class="row justify-content-center">
        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="http://hkdigital.fr/chat/21" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://hkdigital.fr/chat/22" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://hkdigital.fr/chat/23" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>

      <div class="row">
         <% @items.each do |item| %>
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="card h-100">
            <div class="cont-photo-chat">
              <img src="<%= item.image_url %>" class="photo-chat">
            </div>
            <div class="card-body">
              <h4 class="card-title">
                <%= item.title %>
              </h4>
              <h5><%= item.price %> €</h5>
              <p class="card-text"><%= item.description %></p>
            </div>
            <%= link_to "Afficher", product_path(:id => item.id),:class=>"btn btn-secondary" %>
          </div>
        </div>
         <% end %>
      </div>
      <div>
          <br>
          <br>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<%= form_for @item, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>

<p>Titre de l'item</br>
  <%= f.text_field :title %>
</p>

<p>Description du Poster</br>
  <%= f.text_area :description %>
</p>


<p>Prix du Poster</br>
  <%= f.text_field :price %>
</p>


<p>Poster</br>
  <%= f.text_field :image_url %>
</p>


  <%= f.submit "Créer l'Item" %>
<% end %>

app/views/products/show.html.erb
<div class="container">

  <div class="row justify-content-center">

    <div class="col-lg-9">

      <div class="card mt-4">
        <img class="card-img-top img-fluid" src="<%=@item.image_url%>" alt="">
        <div class="card-body">
          <h3 class="card-title"><%=@item.title%></h3>
          <h4><%=@item.price%></h4>
          <p class="card-text"><%=@item.description%></p>
          <%= link_to "Ajouter au panier", addtocart_path(:id => @item.id),:class=>"btn btn-secondary" %>
          <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
          4.0 stars
        </div>
      </div>
      <!-- /.card

      <div class="card card-outline-secondary my-4">
        <div class="card-header">
          Product Reviews
        </div>
        <div class="card-body">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
          <small class="text-muted">Posted by Anonymous on 3/1/17</small>
          <hr>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
          <small class="text-muted">Posted by Anonymous on 3/1/17</small>
          <hr>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
          <small class="text-muted">Posted by Anonymous on 3/1/17</small>
          <hr>
          <a href="#" class="btn btn-success">Leave a Review</a>
        </div>
      </div>
      <!-- /.card -->

    </div>
    <!-- /.col-lg-9 -->

  </div>
  <div>
  <br>
  <br>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="fixed-bottom">
  <footer class="py-2 bg-secondary">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Le Magasin des Posters de Chats</p>
    
    </div>
    <!-- /.container -->
  </footer>
<div class="footer">

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">Posters-de-chat.com<img src="http://catsticker.com/images/dancing-cat.gif" width="60" height="45"></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <% if user_signed_in? %>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="/">Accueil</a>
        </li>
        <li class="nav-item">
          <div class="dropdown show">
              <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-user-circle"></i> Mon profile
              </a>

              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="/showcart">Mon panier</a>
                <a class="dropdown-item" href="/orders">Mes commandes</a>
                <a class="dropdown-item" href="<%=show_user_path(current_user.id)%>">Mon profile</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" data-method="delete" href="/users/sign_out" rel="nofollow">Se déconnecter</a>
              </div>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/showcart">
          <i class="fa fa-shopping-basket"></i>
            <%if current_user.cart%>
          <%=current_user.cart.items.count%>
          <%end%>
        </a>
          </li>
      </ul>

      <% else %>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="/">Accueil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_in">Se connecter</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_up">S'inscrire</a>
        </li>
      </ul>

      <% end %>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<div class="form-container">
  <div class="container">

    <div class="row align-items-center justify-content-center">

      <div class="col-sm-12 col-lg-6 form-box">
        <h1>Mon profil</h1>
        <p>Email: <%=current_user.email%></p>
        <a class="dropdown-item" href="/showcart">Mon panier</a>
        <a class="dropdown-item" href="/orders">Mes commandes</a>
        <% if current_user.admin? %>
          <a class="btn btn-success cart-button" href="/adminv">Admin</a>
        <% end %>
      </div>
    </div>
  </div>
</div>